server:
  port: 9150
swagger:
  config:
    refreshrate: 60000

spring:
  application:
    name: restdoc

    # utilisation de spring consul config aussi, donc dans bootstrap
    consul:
      host: localhost
      port: 8500
      discovery:
        tags: doc
        enabled: true