server:
  port: ${PORT:9100}

spring:
  profiles:
    active: ymlroutes

  sleuth:
    sampler:
      probability: 100

  zipkin:
    baseUrl: http://localhost:9411/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
    restart:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS

logging:
  level:
    org.springframework.cloud.consul: DEBUG