version: '2'
services:
  mongodb:
    image: 'mongo:3'
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2'
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  graylog:
    image: 'graylog/graylog:3.1'
    environment:
      - 'GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/'
    links:
      - 'mongodb:mongo'
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - '9000:9000'
      - '1514:1514'
      - '1514:1514/udp'
      - '12201:12201'
      - '12201:12201/udp'
