server:
  port: ${PORT:9091}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  sleuth:
    sampler:
      probability: 100

  zipkin:
    baseUrl: http://localhost:9411/