server:
  port: ${PORT:9130}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


spring:
  sleuth:
    sampler:
      probability: 100

  kafka:
    producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

  zipkin:
    baseUrl: http://localhost:9411/