server:
  port: ${PORT:9151}

spring:
  application:
    name: spring-admin
  cloud:
    config:
      enabled: false
    consul:
      host: localhost
      port: 8500
      discovery:
        tags: doc
  profiles:
    active:

  boot:
    admin:
      discovery:
        ignored-services: consul


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


